#!/bin/sh
#
# A hook script to verify what is about to be committed. Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if it wants to stop the commit.
#

test_script="../../run_all_tests.sh"
chmod a+x $test_script
sh $test_script


